import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios'
import { Item } from '@/models/item'
import { Gemstone } from '@/models/gemstone.enum'
import { getApiBazaar, getApiItems } from '@/services/hypixel-api'
import { Product } from '@/models/product'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ items, products }: {
  items: Item[],
  products: Product[],
}) {
  return (
    <>
      <Head>
        <title>Bazaar flip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5 max-w-3xl mx-auto bg-indigo-100">
        <h1 className="text-3xl font-bold text-indigo-500">Bazaar flip</h1>

        <div className="flex flex-col gap-2">
          {items
            .map(item => (
              <div key={item.id} className="flex flex-row gap-2">
                <p>
                  {item.name}
                </p>
              </div>
            ))}
        </div>

        <p>{JSON.stringify(products)}</p>

      </main>
    </>
  )
}

export async function getServerSideProps() {

  const itemsRes = await getApiItems();

  const items = itemsRes.data.items
    .filter((item: Item) => Object
      .values(Gemstone).some(gemstone => item.name.includes(gemstone)))
    .sort((a: Item, b: Item) => a.name.localeCompare(b.name));;

  const bazaarRes = await getApiBazaar();

  const products = bazaarRes.data.products;

  return {
    props: {
      items, products
    }, // will be passed to the page component as props
  }
}
